const catalogData = [
	{ id:'n1-1', name: 'Brass Polki Set with full Pearl settings', price: '$55', category: 'necklace sets', imageUrl: './pics/n1-1.png' },
	{ id:'n2-2', name: 'Multicolour Double Layer Brass Polki Set', price: '$80', category: 'necklace sets', imageUrl: './pics/n2-2.png' },
	{ id:'p1-1', name: 'Diamond-shaped Clear Pendant Set', price: '$25', category: 'pendant sets', imageUrl: './pics/p1-1.png' },
	{ id:'p2', name: 'Pink Pendant Set (Chain Available)', price: '$25', category: 'pendant sets', imageUrl: './pics/p2.png' },
	{ id:'p3-1', name: 'Golden Base with Nano settings & Center Pearl', price: '$35', category: 'pendant sets', imageUrl: './pics/p3-1.png' },
	{ id:'p4-1', name: 'Oval AD Clear Pendant Set', price: '$40', category: 'pendant sets', imageUrl: './pics/p4-1.png' },
	{ id:'p13-1', name: 'Oval AD Pink Pendant Set', price: '$40', category: 'pendant sets', imageUrl: './pics/p13-1.png' },
	{ id:'p14', name: 'Oval AD Blue Pendant Set', price: '$40', category: 'pendant sets', imageUrl: './pics/p14.png' },
	{ id:'p18-1', name: 'Oval AD Green Pendant Set', price: '$40', category: 'pendant sets', imageUrl: './pics/p18-1.png' },
	{ id:'p5', name: 'AD Pendant Set (Chain Available)', price: '$25', category: 'pendant sets', imageUrl: './pics/p5.png' },
	{ id:'p6-1', name: 'AD Golden Pearl Pendant Set', price: '$45', category: 'pendant sets', imageUrl: './pics/p6-1.png' },
	{ id:'p7-1', name: 'Droplet AD Clear Pendant Set', price: '$45', category: 'pendant sets', imageUrl: './pics/p7-1.png' },
	{ id:'p7-2', name: 'Droplet AD Pink Pendant Set', price: '$45', category: 'pendant sets', imageUrl: './pics/p7-2.png' },
	{ id:'p16-1', name: 'Droplet AD Blue Pendant Set', price: '$35', category: 'pendant sets', imageUrl: './pics/p16-1.png' },
	{ id:'p8-1', name: 'AD Dangaling Pendant Set', price: '$30', category: 'pendant sets', imageUrl: './pics/p8-1.png' },
	{ id:'p9', name: 'Necklace with Earrings', price: '$45', category: 'pendant sets', imageUrl: './pics/p9.png' },
	{ id:'p20', name: 'Necklace with Earrings', price: '$45', category: 'pendant sets', imageUrl: './pics/p20.jpg' },
	{ id:'p10-1', name: 'Necklace with Earrings', price: '$30', category: 'pendant sets', imageUrl: './pics/p10-1.png' },
	{ id:'p12-1', name: 'AD Big Size Pendant Set', price: '$45', category: 'pendant sets', imageUrl: './pics/p12-1.png' },
	{ id:'p15-1', name: 'Dangling AD Pendant Set', price: '$25', category: 'pendant sets', imageUrl: './pics/p15-1.png' },
	{ id:'p17', name: 'Necklace with Earrings', price: '$35', category: 'pendant sets', imageUrl: './pics/p17.png' },
	{ id:'p19-1', name: 'Yellow Pearl Pendant Set', price: '$40', category: 'pendant sets', imageUrl: './pics/p19-1.png' },
	{ id:'p19-2', name: 'Pink Pearl Pendant Set', price: '$40', category: 'pendant sets', imageUrl: './pics/p19-2.png' },
	{ id:'p21-1', name: 'AD Blue Pendant Set - Premium Quality', price: '$45', category: 'pendant sets', imageUrl: './pics/p21-1.png' },
	{ id:'p21-2', name: 'AD Red Pendant Set - Premium Quality', price: '$45', category: 'pendant sets', imageUrl: './pics/p21-2.png' },
	{ id:'p21-3', name: 'Green Necklace with Earrings', price: '$45', category: 'pendant sets', imageUrl: './pics/p21-3.png' },
	{ id:'e1-1', name: 'Long Droplet Lightweight Earrings Full AD Setting', price: '$30', category: 'earrings', imageUrl: './pics/e1-1.png' },
	{ id:'e2-1', name: 'Green and Red Beautiful earrings', price: '$15 ea.', category: 'earrings', imageUrl: './pics/e2-1.png' },
	{ id:'e4-1', name: 'Long Droplet Lightweight Earrings with AD Setting', price: '$35', category: 'earrings', imageUrl: './pics/e4-1.png' },
	{ id:'e5-1', name: 'Long Droplet Teal Green Lightweight Earrings with AD setting', price: '$45', category: 'earrings', imageUrl: './pics/e5-1.png' },
	{ id:'e5-2', name: 'Long Droplet Blush Pink Lightweight Earrings with AD setting', price: '$45', category: 'earrings', imageUrl: './pics/e5-2.png' },
	{ id:'e5-3', name: 'Long Droplet Clear Lightweight Earrings with AD setting', price: '$45', category: 'earrings', imageUrl: './pics/e5-3.png' },
	{ id:'e6', name: 'Gold Base Studs withdsf AD setting', price: '$15', category: 'earrings', imageUrl: './pics/e6.png' },
	{ id:'b1', name: 'Beautiful Bracelet', price: '$50', category: 'bracelet', imageUrl: './pics/b1.png' },
	{ id:'r1', name: 'Flower Adjustable Ring', price: '$15', category: 'ring', imageUrl: './pics/r1.jpg' },
	{ id:'r2-1', name: 'Adjustable Ring', price: '$15', category: 'ring', imageUrl: './pics/r2-1.png' },
	{ id:'r2-2', name: 'Adjustable Ring', price: '$15', category: 'ring', imageUrl: './pics/r2-2.png' },
	{ id:'r2-3', name: 'Adjustable Ring', price: '$15', category: 'ring', imageUrl: './pics/r2-3.png' },
	{ id:'r3', name: 'Adjustable Ring', price: '$15', category: 'ring', imageUrl: './pics/r3.jpg' },
	{ id:'r4', name: 'Adjustable Ring', price: '$15', category: 'ring', imageUrl: './pics/r4.jpg' },
	{ id:'r5-1', name: 'Blue and Pink Adjustable Rings', price: '$15 ea.', category: 'ring', imageUrl: './pics/r5-1.png' }
];

document.addEventListener('DOMContentLoaded', () => {

});
